theme = 'congo'

defaultContentLanguage = "zh-Hans"
enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true

[services]
  [services.x]
    disableInlineCSS = true

[params]
  colorScheme = "congo"
  defaultAppearance = "light"
  autoSwitchAppearance = true
  enableSearch = true
  enableCodeCopy = true
  enableImageLazyLoading = true
  enableImageWebp = true

  [params.header]
    layout = "basic"
    showTitle = true

  [params.footer]
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
    showScrollToTop = true

  [params.homepage]
    layout = "custom"
    showRecent = true
    recentLimit = 5
    showRecentTitle = "最新文章"

  [params.article]
    showDate = true
    showAuthor = true
    showBreadcrumbs = true
    showDraftLabel = true
    showHeadingAnchors = true
    showPagination = true
    showReadingTime = true
    showTableOfContents = true

  [params.list]
    showBreadcrumbs = true
    showSummary = false
    showTableOfContents = true
    groupByYear = false

  [params.taxonomy]
    showTermCount = true

[[menu.main]]
  name = "文章"
  pageRef = "posts"
  weight = 10

[[menu.main]]
  name = "文档"
  pageRef = "docs"
  weight = 20

[[menu.main]]
  name = "示例"
  pageRef = "samples"
  weight = 30

[[menu.main]]
  name = "用户"
  pageRef = "users"
  weight = 40

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/xufanchn"
  weight = 50
  [menu.main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[menu.main]]
  identifier = "search"
  weight = 99
  [menu.main.params]
    action = "search"

[taxonomies]
  tag = "tags"
