theme = 'hextra'

enableGitInfo = false

[params]
  description = '代码 · 运维 · 思考'
  displayUpdatedDate = true
  dateFormat = '2006-01-02'

  [params.page]
    width = 'normal'

  [params.search]
    enable = true
    type = 'flexsearch'

    [params.search.flexsearch]
      index = 'content'
      tokenize = 'forward'

  [params.theme]
    default = 'system'
    displayToggle = true

  [params.footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = true

  [params.highlight]
    copy = {
      enable = true,
    }

[[menu.main]]
  name = '首页'
  url = '/'
  weight = 1

[[menu.main]]
  name = '文章'
  url = '/posts/'
  weight = 2

[[menu.main]]
  name = '搜索'
  url = '/search/'
  weight = 3

[[menu.main]]
  name = 'GitHub'
  url = 'https://github.com/xufanchn'
  weight = 4

[[menu.sidebar]]
  name = '文章'
  url = '/posts/'
  weight = 1
